In [4]:
import numpy as np
import pandas as pd
import statsmodels as sm
from linearmodels import PanelOLS
from linearmodels import RandomEffects

In [3]:
df = pd.read_csv("c:/Users/dave/Downloads/FDI_and_Poverty/africa_csv.csv")

In [5]:
df

,country_name,year,net_aid,fdi_inflows,nni,inflation,credit,poverty_ratio,education,poverty_gap,bureaucracy
0,Algeria,1960,355050000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.0
1,Algeria,1961,437910000,0.000000,0.000000e+00,3.471720,0.000000,0.0,0.0,0.0,0.0
2,Algeria,1962,397630000,0.000000,0.000000e+00,2.351279,0.000000,0.0,0.0,0.0,0.0
3,Algeria,1963,281910000,0.000000,0.000000e+00,0.549332,0.000000,0.0,0.0,0.0,0.0
4,Algeria,1964,227840000,0.000000,0.000000e+00,1.695183,24.409144,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3295,Zimbabwe,2015,788290000,1.999687,1.515806e+10,0.607814,31.708219,0.0,0.0,0.0,2.8
3296,Zimbabwe,2016,654250000,1.669274,1.555474e+10,2.160993,36.408268,0.0,0.0,0.0,2.8
3297,Zimbabwe,2017,725830000,1.083538,1.627175e+10,6.031593,46.890592,0.0,0.0,0.0,2.8
3298,Zimbabwe,2018,0,2.402015,0.000000e+00,6.031593,48.000307,0.0,0.0,0.0,2.8
3299,Zimbabwe,2019,0,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.0

In [10]:
data = df.set_index(['country_name','year'])
mod = PanelOLS(data.fdi_inflows, data[['net_aid','nni','inflation','credit','education','poverty_ratio','bureaucracy']], entity_effects=True)
res = mod.fit(cov_type='clustered', cluster_entity=True)

In [11]:
res

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:            fdi_inflows   R-squared:                        0.0773
Estimator:                   PanelOLS   R-squared (Between):              0.3403
No. Observations:                3300   R-squared (Within):               0.0773
Date:                Sat, Dec 28 2019   R-squared (Overall):              0.1239
Time:                        20:33:34   Log-likelihood                -1.048e+04
Cov. Estimator:             Clustered
                                        F-statistic:                      38.777
Entities:                          55   P-value                           0.0000
Avg Obs:                       60.000   Distribution:                  F(7,3238)
Min Obs:                       60.000
Max Obs:                       60.000   F-statistic (robust):             8.1156
                                        P-value                           0.0000
Time periods:                      60   Distribution:                  F(7,3238)
Avg Obs:                       55.000
Min Obs:                       55.000
Max Obs:                       55.000

                               Parameter Estimates
=================================================================================
               Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------
net_aid        5.692e-10  4.047e-10     1.4066     0.1596  -2.242e-10   1.363e-09
nni           -7.562e-12  4.439e-12    -1.7035     0.0886  -1.626e-11   1.142e-12
inflation      2.368e-05  8.882e-05     0.2666     0.7898     -0.0002      0.0002
credit           -0.0004     0.0011    -0.3422     0.7322     -0.0024      0.0017
education         0.0106     0.0039     2.7345     0.0063      0.0030      0.0182
poverty_ratio     0.0145     0.0062     2.3445     0.0191      0.0024      0.0265
bureaucracy       1.1527     0.3286     3.5079     0.0005      0.5084      1.7971
=================================================================================

F-test for Poolability: 7.9393
P-value: 0.0000
Distribution: F(54,3238)

Included effects: Entity
PanelEffectsResults, id: 0x14d7a4866c8